name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  job1-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-ci-cd-demo:latest .

  job2-push:
    runs-on: ubuntu-latest
    needs: job1-build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image Again
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-ci-cd-demo:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-ci-cd-demo:latest
